# mise.toml
[tools]
marp-cli="4.2.3"

[env]
TF_WORKSPACE = "development"

[tasks.html]
run = """
marp slides.md --html -o out/slides.html
"""

[tasks.all]
run = """
marp slides.md --html -o out/slides.html
marp slides.md --html -o out/slides.pdf
"""
